language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
    - postgresql
install:
    - pip install -r requirements.txt

script:
    # -  coverage run --source='blog' manage.py test && coverage report && coverage html
    - python manage.py test
