# Generated by Django 3.0.7 on 2020-06-18 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salon_mesage', to='chat.salon'),
        ),
    ]
