# Generated by Django 3.0.7 on 2020-06-25 15:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20200618_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('author',)},
        ),
    ]
